"""users table

Revision ID: d79f3cbe8bec
Revises: 
Create Date: 2024-03-20 10:08:45.975437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd79f3cbe8bec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('MebmbersId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('MebmberPhoto', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('MebmbersId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
